apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.type: nodeport
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: siep-nginx
  name: {{ .Release.Name }}-siep-nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: siep-nginx
    spec:
      containers:
      - image: decyt/siep-nginx
        name: {{ .Release.Name }}-siep-nginx
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
