apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: siep-memcached
  name: {{ .Release.Name }}-siep-memcached
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: siep-memcached
    spec:
      containers:
      - image: memcached:alpine
        name: {{ .Release.Name }}-siep-memcached
        ports:
        - containerPort: 11211
        resources: {}
      restartPolicy: Always
status: {}
